import type { Metadata } from "next";
import Link from "next/link";
import LoginButton from "./components/LoginButton";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Everything Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/velocity"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-sans overflow-x-hidden">
        <div className="relative flex min-h-screen w-full flex-col">
          <nav className="pointer-events-none absolute inset-x-0 top-0 z-30 flex justify-center px-4 pt-4 sm:px-6 sm:pt-6">
            <div className="pointer-events-auto flex w-full max-w-6xl items-center justify-between rounded-2xl border border-white/10 bg-black/40 px-4 py-2 backdrop-blur-md">
              <div className="flex items-center gap-8">
                <Link
                  href="/"
                  className="text-lg font-semibold tracking-tight text-white font-geom"
                >
                  <p className="velocity text-transparent bg-linear-to-r from-sky-700 to-sky-300 bg-clip-text mt-1 ms-6">everything image</p>
                </Link>
                <div className="hidden items-center gap-6 text-sm text-white/70 sm:flex">
                  <Link
                    href="/about"
                    className="transition-colors hover:text-white"
                  >
                    About
                  </Link>
                  <Link
                    href="/contact"
                    className="transition-colors hover:text-white"
                  >
                    Contact
                  </Link>
                </div>
              </div>
              <LoginButton />
            </div>
          </nav>

          <div className="flex-1">
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
