import type { Metadata } from "next";
import Link from "next/link";
import LoginButton from "./components/LoginButton";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Everything Image",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/velocity"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Primary fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Geom:ital,wght@0,300..900;1,300..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Sans Serif */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Raleway:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&family=Anton&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Quicksand:wght@300..700&family=Rubik:ital,wght@0,300..900;1,300..900&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&family=Work+Sans:ital,wght@0,100..900;1,100..900&family=Archivo+Black&family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Outfit:wght@100..900&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Serif */}
        <link
          href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Cinzel:wght@400..900&family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=EB+Garamond:ital,wght@0,400..800;1,400..800&family=Cormorant:ital,wght@0,300..700;1,300..700&family=Zilla+Slab:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Display/Cursive */}
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Pacifico&family=Dancing+Script:wght@400..700&family=Indie+Flower&family=Lobster&family=Righteous&family=Permanent+Marker&family=Abril+Fatface&family=Bangers&family=Caveat:wght@400..700&family=Shadows+Into+Light&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Italic/Script */}
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Allura&family=Satisfy&family=Kaushan+Script&family=Alex+Brush&family=Cookie&family=Sacramento&family=Tangerine:wght@400;700&family=Courgette&family=Bad+Script&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Oxford/Classic */}
        <link
          href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Lora:ital,wght@0,400..700;1,400..700&family=Cardo:ital,wght@0,400;0,700;1,400&family=Spectral:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Old+Standard+TT:ital,wght@0,400;0,700;1,400&family=Crimson+Pro:ital,wght@0,200..900;1,200..900&family=Bentham&family=Unna:ital,wght@0,400;0,700;1,400;1,700&family=Neuton:ital,wght@0,200;0,300;0,400;0,700;0,800;1,400&family=Sorts+Mill+Goudy:ital@0;1&display=swap"
          rel="stylesheet"
        />
        {/* Watermark fonts - Additional Cursive */}
        <link
          href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Yellowtail&family=Pinyon+Script&family=Marck+Script&family=Mr+Dafoe&family=Rochester&family=Playball&family=Leckerli+One&family=Zeyada&family=Damion&family=Herr+Von+Muellerhoff&family=Niconne&family=Italianno&family=Grand+Hotel&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-sans overflow-x-hidden">
        <div className="relative flex min-h-screen w-full flex-col">
          <nav className="pointer-events-none absolute inset-x-0 top-0 z-30 flex justify-center px-4 pt-4 sm:px-6 sm:pt-6">
            <div className="pointer-events-auto flex w-full max-w-6xl items-center justify-between rounded-2xl border border-white/10 bg-black/40 px-4 py-2 backdrop-blur-md">
              <div className="flex items-center gap-8">
                <Link
                  href="/"
                  className="text-lg font-semibold tracking-tight text-white font-geom"
                >
                  <p className="velocity text-transparent bg-linear-to-r from-sky-700 to-sky-300 bg-clip-text mt-1 ms-6">everything image</p>
                </Link>
                <div className="hidden items-center gap-6 text-sm text-white/70 sm:flex">
                  <Link
                    href="/about"
                    className="transition-colors hover:text-white"
                  >
                    About
                  </Link>
                  <Link
                    href="/contact"
                    className="transition-colors hover:text-white"
                  >
                    Contact
                  </Link>
                </div>
              </div>
              <LoginButton />
            </div>
          </nav>

          <div className="flex-1">
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
